### ISSUE TITLE
Add work-around (in README) for when require('devtron').install() does not resolve in devtools

### ISSUE THREAD

**Issue by justin-calleja** [electron/devtron#99] opened 2017-04-19 16:08 UTC
When running the [quickstart](https://github.com/electron/electron-quick-start) example, everything works.

When using a setup similar to the one in this [blog post](https://medium.freecodecamp.com/building-an-electron-application-with-create-react-app-97945861647c), i.e. serving HTML through Webpack dev server, the 'devtron' module is not resolvable for me from renderer's process's Console (I can resolve it from main process's REPL when running electron with `--interactive`).

To get around this, since it works from the main process, one can add: `require('devtron').install()` in the main process's file, run it once and then remove it.

Is this worth documenting in README.md?

**Comment by mandiwise** [comment] 2017-05-15 02:33
Also worth documenting with this is that `.install()` called before the ready event of the app module is emitted.

**Comment by akomm** [comment] 2017-08-02 13:40
@justin-calleja neither of your links posted contain any usage of `require('devtron').install()`.

**Comment by justin-calleja** [comment] 2017-08-02 13:47
@akomm they might not (forgot what this was about). But that's not the point. I had apparently got around the issue by using `require('devtron').install()` in the main process and this issue is saying: "is it worth documenting that?"

**Comment by akomm** [comment] 2017-08-02 13:56
I see, I just wanted to reproduce the issue by checking the diff between the "working" and "not working". I used it right ahead after 'ready' event, but I think it should be documented - why not?

**Comment by justin-calleja** [comment] 2017-08-02 18:01
@akomm if it works OOTB now, no need to document it :)

I haven't tried it out myself but am closing this issue based on your feedback. Thanks!

**Comment by akomm** [comment] 2017-08-03 09:46
If you do not place it correctly, it is not working OOTB. A simple note won't kill anybody. 

I also came about an issue installing devtron after bundling with webpack using target "electron-main". The problem is how __dirname is resolved in this case. You have to set webpack to not resolving __dirname relative to context, instead let node resolve it, otherwise devtron fails to load the manifest:

```js
// in your webpack config for main process
{
   target: 'electron-main',
   node: {
      __dirname: false,
    }
}
```
https://webpack.js.org/configuration/node/#node-__dirname

While I understand, that this is not devtron, webpack is very common and it won't kill anybody to make a note "when you use webpack, consider adding ...".

**Comment by quantummkv** [comment] 2017-08-16 19:49
while trying to use devtron with webpack, i get the following error: 

```
Error: ENOENT: no such file or directory, open 'E:\electron\nighthawk\dist\manifest.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at getManifestFromPath (E:\electron\nighthawk\node_modules\electron\dist\resources\electron.asar\browser\chrome-extension.js:34:26)
    at Function.BrowserWindow.addDevToolsExtension (E:\electron\nighthawk\node_modules\electron\dist\resources\electron.asar\browser\chrome-
extension.js:373:22)
    at App.app.on (E:\electron\nighthawk\dist\main.js:445:19)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```

i have set __dirname to false, still i am getting this error.

**Comment by akomm** [comment] 2017-08-22 10:48
Yes the issue is, that when you use webpack, the __dirname is resolved at runtime on the compiled file. I currently have the following woraround for this (only relevant config parts inserted):

```js
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = env => {
  const copyFiles = [/* ... */];

  if (env === 'development') {
    copyFiles.push(
      {from: path.resolve(__dirname, 'node_modules/devtron/manifest.json')},
      {
        from: path.resolve(__dirname, 'node_modules/devtron/out/browser-globals.js'),
        to: path.resolve(__dirname, 'dist/out'),
      }
    );
  }

  return {
    entry: './src/main.js',
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: 'main.js',
    },
    target: 'electron-main',
    plugins: [
      new CopyWebpackPlugin(copyFiles),
    ],
    node: {
      __dirname: false,
      __filename: false,
    },
  };
};
```

1. Make sure, that webpack does not replace __dirname by setting the false as mentioned.
2. make sure that the copy _target_ for _devtron/manifest.json_ is the same folder as your compiled main process js file.
3. make sure that the copy _target_ for the _devtron/out/browser-globals.js_ is _out/browser-globals.js_ relative to your compiled main process js file.

**Comment by codebytere** [comment] 2018-04-11 14:47
i'll PR this in today

**Closed** 2018-04-12 21:40 UTC

**Comment by FuriouZz** [comment] 2018-05-01 00:12
An alternative solution is to remove `devtron` module from webpack bundle. Webpack will let the `require('devtron')` in the main compiled file.

```
config.externals = [
    function(context, request, callback) {
      if (request.match(/vue-devtools|devtron/)) {
        return callback(null, 'commonjs ' + request)
      }

      callback()
    }
  ]
```

**Comment by agjs** [comment] 2019-02-05 14:01
> An alternative solution is to remove `devtron` module from webpack bundle. Webpack will let the `require('devtron')` in the main compiled file.
> 
> ```js
> config.externals = [
>   function(context, request, callback) {
>     if (request.match(/vue-devtools|devtron/)) {
>       return callback(null, 'commonjs ' + request)
>     }
> 
>     callback()
>   }
> ]
> ```

Worked for me, thanks!
